import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import { Box, Button, Container, Flex, Heading, Text } from "@chakra-ui/react";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import About from "@/components/About";
import LatestArticles from "@/components/LatestArticle";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Internet Folks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <About></About>
      <LatestArticles></LatestArticles>
      <Footer></Footer>
    </>
  );
}
